[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_VERSION = "18.18.0"
NODE_ENV = "production"
PORT = "3000" 